import { Testing } from 'projen/lib/testing';
import { TerraformBaseProject, TerraformStackProject } from '../src/terraform';

describe('TerraformBaseProject', () => {
  it('should create a basic Terraform project', () => {
    const project = new TerraformBaseProject({
      name: 'test-terraform-base',
    });

    const snapshot = Testing.synth(project);

    expect(snapshot['versions.tf']).toContain('terraform {');
    expect(snapshot['versions.tf']).toContain('required_version = ">= 1.6.0"');
    expect(snapshot['versions.tf']).toContain('Generated by projen');
    expect(snapshot['.gitignore']).toContain('.terraform/');
    expect(snapshot['.gitignore']).toContain('*.tfstate');
  });

  it('should accept custom Terraform version', () => {
    const project = new TerraformBaseProject({
      name: 'test-terraform-base-custom',
      terraformVersion: '1.5.0',
    });

    const snapshot = Testing.synth(project);

    expect(snapshot['versions.tf']).toContain('required_version = ">= 1.5.0"');
    expect(snapshot['versions.tf']).toContain('Generated by projen');
  });
});

describe('TerraformStackProject', () => {
  it('should create a basic Terraform stack', () => {
    const project = new TerraformStackProject({
      name: 'test-terraform-stack',
    });

    const snapshot = Testing.synth(project);

    // Check base Terraform files
    expect(snapshot['versions.tf']).toContain('terraform {');
    expect(snapshot['.gitignore']).toContain('.terraform/');

    // Check stack files
    expect(snapshot['main.tf']).toContain('# Main Terraform configuration');
    expect(snapshot['variables.tf']).toContain('# Terraform variables');
    expect(snapshot['outputs.tf']).toContain('# Terraform outputs');
  });
});
