import { Project, ProjectOptions, TextFile } from 'projen';
import { TerraformProvider } from './providers';

/**
 * Options for Terraform base project.
 */
export interface TerraformBaseProjectOptions extends ProjectOptions {
  /**
   * Minimum required Terraform version.
   * @default "1.6.0"
   */
  readonly terraformVersion?: string;

  /**
   * Terraform provider configuration.
   */
  readonly provider?: TerraformProvider;
}

/**
 * Base Terraform project that provides common Terraform configuration.
 */
export class TerraformBaseProject extends Project {
  private _provider?: TerraformProvider;
  private readonly _terraformVersion: string;

  constructor(options: TerraformBaseProjectOptions) {
    super(options);

    // Store the provider and terraform version
    this._provider = options.provider;
    this._terraformVersion = options.terraformVersion ?? '1.6.0';

    // Create versions.tf with Terraform version constraint
    new TextFile(this, 'versions.tf', {
      //marker: true,
      //readonly: true,
      lines: [
        '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen". ~~',
        '',
        'terraform {',
        `  required_version = ">= ${this._terraformVersion}"`,
        '}',
        '',
      ],
    });

    // Add Terraform-specific patterns to .gitignore
    this.gitignore.addPatterns(
      '.terraform/',
      '*.tfstate',
      '*.tfstate.*',
      '.terraform.lock.hcl',
      'terraform.tfvars',
      '*.tfvars',
      'override.tf',
      'override.tf.json',
      '*_override.tf',
      '*_override.tf.json',
    );

    // Add basic Terraform tasks
    this.addTask('terraform:init', {
      description: 'Initialize Terraform working directory',
      exec: 'terraform init',
    });

    this.addTask('terraform:format', {
      description: 'Format Terraform configuration files',
      exec: 'terraform fmt -recursive',
    });

    this.addTask('terraform:validate', {
      description: 'Validate Terraform configuration',
      exec: 'terraform validate',
    });
  }

  /**
   * Add a provider to this Terraform project.
   * Only one provider per project is allowed.
   */
  public addProvider(provider: TerraformProvider): void {
    if (this._provider) {
      throw new Error('Only one provider per Terraform project is allowed');
    }
    this._provider = provider;
    this.generateProviderFile();
  }

  /**
   * Get the current provider.
   */
  public get provider(): TerraformProvider | undefined {
    return this._provider;
  }

  public preSynthesize(): void {
    super.preSynthesize();
    if (this._provider) {
      this.generateProviderFile();
    }
  }

  /**
   * Generate the provider.tf file if a provider is configured.
   */
  private generateProviderFile(): void {
    if (!this._provider) {
      return;
    }

    new TextFile(this, 'provider.tf', {
      lines: [
        '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen". ~~',
        '',
        'terraform {',
        '  required_providers {',
        `    ${this._provider.providerAlias()} = {`,
        `      source  = "${this._provider.providerSource()}"`,
        `      version = "${this._provider.versionConstraint()}"`,
        '    }',
        '  }',
        '}',
        '',
        ...this._provider.generateProviderBlock(),
        '',
      ],
    });
  }
}
